apiVersion: delivery.ocm.software/v1alpha1
kind: Diffusion
metadata:
  name: sock-shop
  namespace: ocm-system
spec:
  interval: 10m0s
  prune: true
  componentVersionRef:
    name: sock-shop
    namespace: ocm-system
  resourceSelector:
    skipRoot: true
    followReferences: true
    matchSelector:
    - field: "type"
      values:
      - kustomize.ocm.fluxcd.io
  pipelineTemplateRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
    path: ./01-weaveworks-sock-shop/conf/sockshop-pipeline-template.yaml
  values: {}
